// filter projecten
$(function(){
    $("li:contains('ALL')").click(function(){
        $('div[class*="filter"]').show();
    });
    $("li:contains('APP')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-app").show();
    });
    $("li:contains('IOT')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-iot").show();
    });
    $("li:contains('DI')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-di").show();
    });
    $("li:contains('CCS')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-ccs").show();
    });
    $("li:contains('AI')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-ai").show();
    });
    $("li:contains('HACKATHON')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-hackathon").show();
    });
    $("li:contains('OTHER')").click(function(){
        $('div[class*="filter"]').hide();
        $(".filter-other").show();
    });
});
